<?php

/* Stub generated by Install script. */
class CRM_Utils_Hook_NoCms extends CRM_Utils_Hook {
    public function invokeViaUF($numParams, &$arg1, &$arg2, &$arg3, &$arg4, &$arg5, &$arg6, $fnSuffix)
    {
        return '';
    }

}


